version: '3.4'

services:
  workerservice:
    image: nickmartin1ee7/uwuifydiscordbotworkerservice:dev
    environment:
        - DiscordSettings__Token
        - DiscordSettings__Status
        - DiscordSettings__ShardManagerUri
        - LoggerConfig__ServerUri
        - LoggerConfig__ApiKey
    depends_on:
        - seq
        - shardmanager
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        preferences:
          - spread: node.lables.slot
          - spread: node.id

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8085:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - "node.role==manager"

  shardmanager:
    image: nickmartin1ee7/discordbotshardmanagerwebapi:dev
    environment:
        - ShardManager__MaxShards
        - ShardManager__InternalShards
    ports:
        - 8086:80
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - "node.role==manager"

volumes:
  seqdata:
