version: '3.4'

services:
    workerservice:
        image: nickmartin1ee7/uwuifydiscordbotworkerservice:latest
        environment:
            - ConnectionStrings__DataContext
            - DiscordSettings__DebugServerId
            - DiscordSettings__Status
            - DiscordSettings__Token
            - DiscordSettings__Shards
            - DiscordSettings__MetricsUri
            - DiscordSettings__MetricsToken
            - DiscordSettings__ProfanityWords
            - DiscordSettings__RateLimitingRenewalJobExecutionInMilliSeconds
            - DiscordSettings__RateLimitingMaxUsages
            - DiscordSettings__RateLimitingUsageFallOffInMilliSeconds
            - DiscordSettings__FortuneUri
            - DiscordSettings__FortuneApiKey
            - DiscordSettings__HoneyPotUsername
            - DiscordSettings__HoneyPotPassword
            - DiscordSettings__HoneyPotHost
            - DiscordSettings__HoneyPotPort
        secrets:
            - UwuifyHealthCheckUri
        depends_on:
            - seq
            - postgres
        healthcheck:
            test: curl -f $$(cat /run/secrets/UwuifyHealthCheckUri) || exit 1
            start_period: 0s
            interval: 1m
        deploy:
            replicas: 1
            mode: replicated
            update_config:
                parallelism: 1
            restart_policy:
                condition: any
                delay: 5s
            placement:
                preferences:
                    - spread: node.lables.slot
                    - spread: node.id

    seq:
        image: datalust/seq:latest
        ports:
            - 11080:80
        environment:
            - ACCEPT_EULA=Y
        volumes:
            - seqdata:/data
        deploy:
            replicas: 1
            mode: replicated
            update_config:
                parallelism: 1
            restart_policy:
                condition: any
            placement:
                constraints:
                    - "node.role==manager"

    postgres:
        image: postgres:latest
        ports:
            - 11432:5432
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        volumes:
            - postgresdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 11090:80
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD
        depends_on:
            - postgres

volumes:
    seqdata:
    postgresdata:

secrets:
    UwuifyHealthCheckUri:
        external: true
