version: '3.4'

services:
  uwuify.discordbot.workerservice:
    image: ${DOCKER_REGISTRY-}uwuifydiscordbotworkerservice
    build:
      context: .
      dockerfile: Uwuify.DiscordBot.WorkerService/Dockerfile
    environment:
        - DiscordSettings__Token
        - DiscordSettings__Status
        - DiscordSettings__Shards
        - DiscordSettings__MetricsUri
        - DiscordSettings__MetricsToken
        - DiscordSettings__ProfanityWords
    secrets:
        - UwuifyHealthCheckUri
    depends_on:
        - seq
    healthcheck:
        test: curl -f $$(cat /run/secrets/UwuifyHealthCheckUri) || exit 1
        start_period: 0s
        interval: 1m

  seq:
    image: datalust/seq:latest
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

volumes:
  seqdata:

secrets:
  UwuifyHealthCheckUri:
    external: true
