version: '3.4'

services:
  workerservice:
    image: nickmartin1ee7/uwuify-discordbot:latest
    environment:
      - DiscordSettings__Token=${DISCORD_TOKEN}
    depends_on:
        - seq
  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

volumes:
  seqdata: