version: '3.4'

services:
  uwuify.discordbot.workerservice:
    image: ${DOCKER_REGISTRY-}uwuifydiscordbotworkerservice
    build:
      context: .
      dockerfile: Uwuify.DiscordBot.WorkerService/Dockerfile
    environment:
          - DiscordSettings__Token
          - Serilog__ApiKey
    depends_on:
        - seq

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

volumes:
  seqdata:
