version: '3.4'

services:
  workerservice:
    image: nickmartin1ee7/uwuifydiscordbotworkerservice:latest
    environment:
      - DiscordSettings__Token
      - Serilog__ApiKey
      - ShardCount
    depends_on:
        - seq
        - uwuify.shardmanager.webapi
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  uwuify.shardmanager.webapi:
    image: nickmartin1ee7/uwuifyshardmanagerwebapi:latest
    environment:
        - ShardCount
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

volumes:
  seqdata: