version: '3.4'

services:
  uwuify.discordbot.workerservice:
    image: ${DOCKER_REGISTRY-}uwuifydiscordbotworkerservice
    build:
      context: .
      dockerfile: Uwuify.DiscordBot.WorkerService/Dockerfile
    environment:
        - DiscordSettings__Token
        - DiscordSettings__Status
        - DiscordSettings__Shards
        - LoggerConfig__ServerUri
    depends_on:
        - seq

  seq:
    image: datalust/seq:latest
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

volumes:
  seqdata:
