version: '3.4'

services:
    uwuify.discordbot.workerservice:
        image: ${DOCKER_REGISTRY-}uwuifydiscordbotworkerservice
        build:
            context: .
            dockerfile: Uwuify.DiscordBot.WorkerService/Dockerfile
        environment:
            - ConnectionStrings__DataContext=Server=postgres;Port=5432;Database=DataContext;User Id=sa;Password=sa;Include Error Detail=True;
            - DiscordSettings__DebugServerId
            - DiscordSettings__Status=Testing Now
            - DiscordSettings__Token
            - DiscordSettings__Shards=1
            - DiscordSettings__MetricsUri=https://seq
            - DiscordSettings__MetricsToken=
            - DiscordSettings__ProfanityWords=
            - DiscordSettings__RateLimitingRenewalJobExecutionInMilliSeconds=5000
            - DiscordSettings__RateLimitingMaxUsages=1
            - DiscordSettings__RateLimitingUsageFallOffInMilliSeconds=30000
            - DiscordSettings__FortuneUri=https://fortune
            - DiscordSettings__FortuneApiKey
            - DiscordSettings__HoneyPotUsername=root
            - DiscordSettings__HoneyPotPassword=root
            - DiscordSettings__HoneyPotHost=cowrie
            - DiscordSettings__HoneyPotPort=2223
        depends_on:
            - seq
            - postgres

    seq:
        image: datalust/seq:latest
        ports:
            - 8080:80
        environment:
            - ACCEPT_EULA=Y
        volumes:
            - seqdata:/data

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=DataContext
            - POSTGRES_USER=sa
            - POSTGRES_PASSWORD=sa
        volumes:
            - postgresdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 9090:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        depends_on:
            - postgres

volumes:
    seqdata:
    postgresdata: