version: '3.4'

services:
  workerservice:
    image: nickmartin1ee7/uwuifydiscordbotworkerservice:latest
    environment:
        - DiscordSettings__Token
        - DiscordSettings__Status
        - DiscordSettings__InternalShards
        - Serilog__ApiKey
    depends_on:
        - seq
        - shardmanager
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 30s

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  shardmanager:
    image: nickmartin1ee7/uwuifyshardmanagerwebapi:latest
    environment:
        - ShardManager__ShardCount
    ports:
        - 8081:80
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

volumes:
  seqdata:
