name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish:

    runs-on: self-hosted

    steps:
    - name: Update Git repo
      run: git pull
    - name: Sanity Check
      run: find .
    - name: Docker Compose
      env:
        SUDOER: ${{ secrets.SUDO_CD }}
      run: 
        echo "$SUDOER" | xargs sudo -S su && sudo docker-compose -p uwuifyenvironment up -d --force-recreate --remove-orphans seq uwuify.discordbot.workerservice
    - name: Clean Bash History
      continue-on-error: true
      run:
        cat /dev/null > ~/.bash_history && history -cw
