name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish:

    runs-on: self-hosted

    steps:
    - name: Sanity Check
      run: find .
    - name: Docker Compose
      env:
        SUDOER:  ${{ secrets.SUDO_CD }}
      run: 
        echo "$SUDOER" | xargs sudo -S docker-compose  -p uwuifyenvironment up -d --no-build --force-recreate --remove-orphans  seq uwuify.discordbot.workerservice
    - name: Clean Bash History
      continue-on-error: true
      run:
        cat /dev/null > ~/.bash_history && history -cw
