name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Stop Discord Bot Service
      env:
        SUDOER:  ${{ secrets.SUDO_CD }}
      run: 
        echo "$SUDOER" | xargs sudo -S service uwuify-discord-bot stop
    - name: Publish
      run: dotnet publish --no-restore -c Release -o $HOME/Uwuify
    - name: Start Discord Bot service
      env:
        SUDOER:  ${{ secrets.SUDO_CD }}
      run:
        echo "$SUDOER" | xargs sudo -S service uwuify-discord-bot restart
    - name: Clean Bash History
      continue-on-error: true
      run:
        cat /dev/null > ~/.bash_history && history -c && && history -w
