name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Stop service
      run: 
    - name: Build
      run: dotnet build --no-restore -c Release -o $HOME/Uwuify
    - name: Test
      run: dotnet test --no-build --verbosity normal
