name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore Uwuify.DiscordBot.sln

    - name: Build
      run: dotnet build --no-restore Uwuify.DiscordBot.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal Uwuify.DiscordBot.sln

  publish:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESSTOKEN }}
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Pull source code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker buildx build --platform linux/arm64 -f "Uwuify.DiscordBot.WorkerService/Dockerfile" --force-rm -t nickmartin1ee7/uwuifydiscordbotworkerservice:latest --load .
    
    - name: Publish Docker image
      run: docker push nickmartin1ee7/uwuifydiscordbotworkerservice:latest
    
    - name: Trigger production image pull
      run: curl --location --request POST 'http://localhost:9000/api/webhooks/ed3e9573-7ae6-4fe4-afc6-d73e5cd509bc'
