name: Production CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore Uwuify.DiscordBot.sln

    - name: Build
      run: dotnet build --no-restore Uwuify.DiscordBot.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal Uwuify.DiscordBot.sln

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESSTOKEN }}
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Pull Source Code
      uses: actions/checkout@v2
      with:
        submodules: 'true'
      
    - name: Build Docker Image (DiscordBot)
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker buildx build --platform linux/arm64,linux/amd64 -f "Uwuify.DiscordBot.WorkerService/Dockerfile" --force-rm -t nickmartin1ee7/uwuifydiscordbotworkerservice:latest --push .

  deployment:
    runs-on: self-hosted
    needs: publish

    steps:
    - name: Trigger Production Image Pull
      if: ${{ github.ref == 'refs/heads/main' }}
      run: curl --location --request POST '${{ secrets.PROD_WEBHOOK_URI }}'